In [ ]:
l1=[1,2,3,4]
l2=[1,2,3,4]
l3=l1+l2
print(l3)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
import numpy as np
npl1=np.array([1,2,3,4])
npl2=np.array([1,2,3,4])
npl3=npl1+npl2
print(npl3)

[2 4 6 8]


In [ ]:
li=['a',123,3.16,'hello']

In [ ]:
# array is a collection of data of same datatype

In [ ]:
npl4=np.array([1,2,3,4])
npl5=np.array([1,2,3,4])
npl6=npl4*npl5
print(npl6)

[ 1  4  9 16]


In [ ]:
# Arr = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]]


# and the given lists are as follows :


# lst  = [1,2,3,4,5]              True, as it matches with the row 0.

#        [16,17,20,19,18]         False, as it doesn’t match with any row.

#        [3,2,5,-4,5]             False, as it doesn’t match with any row.

#        [11,12,13,14,15]         True, as it matches with the row 2.

In [ ]:
#How to Remove rows in Numpy array that contains non-numeric values?
#Find the number of occurrences of a sequence in a NumPy array
'''Arr = [[2,8,9,4],
       [9,4,9,4],
       [4,5,9,7],
       [2,9,4,3]]
and the seq = [9,4] then output is 3'''

#How to check whether specified values are present in NumPy array?

#Counts the number of non-zero values in the array
#Trim the leading and/or trailing zeros from a 1-D array np.arr([0,0,0,0,1,4,5,7,0,3,6,0,0,0,0])

#Reverse a numpy array
#How to make a NumPy array read-only?
#Replace NumPy array elements that doesn’t satisfy the given condition
#Return the indices of elements where the given condition is satisfied
#Replace NaN values with average of columns
'''np.array([[1.3, 2.5, 3.6, np.nan],
            [2.6, 3.3, np.nan, 5.5],
            [2.1, 3.2, 5.4, 6.5]])'''
#Replace negative value with zero in numpy array

In [ ]:
import numpy as np

a=np.array((1,2,3,4))
print(a)
g=np.moveaxis(a,0,-1).shape
print(g)

[1 2 3 4]
(4,)


In [ ]:
import numpy as geek

arr = geek.zeros((1, 2, 3, 4))

gfg = geek.moveaxis(arr, -1, 0).shape

print (gfg)

(4, 1, 2, 3)
