# NumPy Basics

NumPy (`Numerical Python`) is the core library for numerical computing in Python. Its main
object is the `ndarray` — a fast, memory-efficient, multi-dimensional array that supports
vectorized operations (no explicit Python loops needed), unlike a plain Python `list`.

1. NumPy Overview
2. `ndarray`: Properties, Purpose & Types
3. Class & Attributes of the `ndarray` Object
4. Basic Operations
5. Accessing Array Elements: Indexing, Slicing, Iteration, Boolean Indexing
6. Copy and Views
7. Universal Functions (ufuncs)
8. Shape Manipulation & Broadcasting
9. Linear Algebra with NumPy
10. Stacking and Resizing

## 1. NumPy Overview

NumPy arrays are stored in one contiguous block of memory with a single data type, so operations
run as compiled C code instead of a Python-level loop — this makes them both faster and more
memory-efficient than lists for numerical work. The convention is to import it as `np`.

In [1]:
# Solution
import numpy as np
import time

# A quick speed comparison: squaring a million numbers
size = 1_000_000
python_list = list(range(size))
numpy_array = np.arange(size)

start = time.perf_counter()
squared_list = [x * x for x in python_list]
list_time = time.perf_counter() - start

start = time.perf_counter()
squared_array = numpy_array ** 2
numpy_time = time.perf_counter() - start

print(f"Python list comprehension: {list_time:.4f}s")
print(f"NumPy vectorized op:       {numpy_time:.4f}s")
print("NumPy version:", np.__version__)

Python list comprehension: 0.0459s
NumPy vectorized op:       0.0028s
NumPy version: 2.5.2


## 2. `ndarray`: Properties, Purpose & Types

An `ndarray` can be created from a Python list/tuple, or with NumPy's own constructors. All
elements share a single `dtype` (data type), which is what makes vectorized math possible.

In [2]:
# Solution
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
ranged = np.arange(0, 10, 2)          # start, stop, step
evenly_spaced = np.linspace(0, 1, 5)  # start, stop, num points
identity = np.eye(3)

print("1D array:", arr_1d)
print("2D array:\n", arr_2d)
print("zeros(2,3):\n", zeros)
print("ones(3,2):\n", ones)
print("arange(0,10,2):", ranged)
print("linspace(0,1,5):", evenly_spaced)
print("eye(3):\n", identity)
print("dtype of arr_1d:", arr_1d.dtype)
print("dtype of a float array:", np.array([1.5, 2.5]).dtype)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
zeros(2,3):
 [[0. 0. 0.]
 [0. 0. 0.]]
ones(3,2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
arange(0,10,2): [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]
eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dtype of arr_1d: int64
dtype of a float array: float64


## 3. Class & Attributes of the `ndarray` Object

Every `ndarray` carries metadata describing its shape and memory layout: `ndim` (number of
dimensions), `shape` (size along each dimension), `size` (total element count), `dtype`,
`itemsize` (bytes per element), and `nbytes` (total bytes).

In [3]:
# Solution
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("type:", type(matrix))
print("ndim:", matrix.ndim)
print("shape:", matrix.shape)
print("size:", matrix.size)
print("dtype:", matrix.dtype)
print("itemsize (bytes):", matrix.itemsize)
print("nbytes (total bytes):", matrix.nbytes)

type: <class 'numpy.ndarray'>
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize (bytes): 8
nbytes (total bytes): 96


## 4. Basic Operations

Arithmetic on arrays is element-wise and vectorized. A scalar is automatically "broadcast" across
every element. NumPy also provides aggregate functions like `sum`, `mean`, `min`, `max`, `std`.

In [4]:
# Solution
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a * 3 (scalar broadcast):", a * 3)
print("a > 2 (comparison):", a > 2)

print("sum:", a.sum())
print("mean:", a.mean())
print("min:", a.min(), "max:", a.max())
print("std:", a.std())

a + b: [11 22 33 44]
a - b: [ -9 -18 -27 -36]
a * b: [ 10  40  90 160]
a / b: [0.1 0.1 0.1 0.1]
a * 3 (scalar broadcast): [ 3  6  9 12]
a > 2 (comparison): [False False  True  True]
sum: 10
mean: 2.5
min: 1 max: 4
std: 1.118033988749895


## 5. Accessing Array Elements: Indexing, Slicing, Iteration, Boolean Indexing

`ndarray` supports Python-style indexing/slicing (extended to multiple dimensions with commas),
direct iteration, and boolean-array indexing to filter elements matching a condition.

In [5]:
# Solution
grid = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("element [1,2]:", grid[1, 2])
print("row 1:", grid[1])
print("column 1:", grid[:, 1])
print("slice rows 0-1, cols 1-2:\n", grid[0:2, 1:3])

print("iterating rows:")
for row in grid:
    print(" ", row)

print("iterating every element with nditer:")
for value in np.nditer(grid):
    print(" ", value, end="")
print()

mask = grid % 2 == 0
print("boolean mask (even):\n", mask)
print("even elements via boolean indexing:", grid[mask])

element [1,2]: 6
row 1: [4 5 6]
column 1: [2 5 8]
slice rows 0-1, cols 1-2:
 [[2 3]
 [5 6]]
iterating rows:
  [1 2 3]
  [4 5 6]
  [7 8 9]
iterating every element with nditer:
  1  2  3  4  5  6  7  8  9
boolean mask (even):
 [[False  True False]
 [ True False  True]
 [False  True False]]
even elements via boolean indexing: [2 4 6 8]


## 6. Copy and Views

Slicing an `ndarray` returns a **view** — it shares the same underlying memory, so modifying the
view changes the original. `.copy()` makes an independent copy. `.view()` explicitly creates a
new array object that still shares memory with the original.

In [6]:
# Solution
original = np.array([1, 2, 3, 4, 5])

view_slice = original[1:4]
view_slice[0] = 99
print("after modifying a slice, original:", original)  # original changed too

copy_arr = original.copy()
copy_arr[0] = -1
print("after modifying the copy, original:", original)  # original unaffected
print("copy_arr:", copy_arr)

explicit_view = original.view()
explicit_view[-1] = 100
print("after modifying explicit view, original:", original)  # original changed

print("view_slice.base is original:", view_slice.base is original)
print("copy_arr.base is None:", copy_arr.base is None)

after modifying a slice, original: [ 1 99  3  4  5]
after modifying the copy, original: [ 1 99  3  4  5]
copy_arr: [-1 99  3  4  5]
after modifying explicit view, original: [  1  99   3   4 100]
view_slice.base is original: True
copy_arr.base is None: True


## 7. Universal Functions (ufuncs)

Ufuncs apply a function element-wise across an array without writing an explicit loop —
`np.sqrt`, `np.exp`, `np.sin`, and operators like `np.add`/`np.multiply` are all ufuncs.

In [7]:
# Solution
values = np.array([1, 4, 9, 16, 25])

print("sqrt:", np.sqrt(values))
print("exp:", np.exp(np.array([0, 1, 2])))
print("sin:", np.sin(np.array([0, np.pi / 2, np.pi])))

x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print("np.add(x, y):", np.add(x, y))
print("np.multiply(x, y):", np.multiply(x, y))

# a ufunc replaces an explicit Python loop:
loop_result = [v ** 0.5 for v in values]
print("equivalent Python loop result:", loop_result)

sqrt: [1. 2. 3. 4. 5.]
exp: [1.         2.71828183 7.3890561 ]
sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
np.add(x, y): [11 22 33]
np.multiply(x, y): [10 40 90]
equivalent Python loop result: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]


## 8. Shape Manipulation & Broadcasting

`reshape` changes an array's shape without changing its data; `ravel`/`flatten` collapse it back
to 1D; `transpose`/`.T` swaps axes. Broadcasting lets NumPy operate on arrays of different but
compatible shapes by "stretching" the smaller one, without actually copying data.

In [8]:
# Solution
flat = np.arange(12)
reshaped = flat.reshape(3, 4)
print("reshaped to (3,4):\n", reshaped)
print("raveled back to 1D:", reshaped.ravel())
print("transposed (4,3):\n", reshaped.T)

# Broadcasting: a (3,4) array plus a (4,) array -> the 1D array is broadcast across every row
row_addend = np.array([100, 200, 300, 400])
print("broadcast add (3,4) + (4,):\n", reshaped + row_addend)

# Broadcasting: a (3,1) column plus a (1,4) row -> both stretch to produce a (3,4) result
column = np.array([[0], [10], [20]])
row = np.array([[1, 2, 3, 4]])
print("broadcast (3,1) + (1,4):\n", column + row)

reshaped to (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
raveled back to 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed (4,3):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
broadcast add (3,4) + (4,):
 [[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
broadcast (3,1) + (1,4):
 [[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


## 9. Linear Algebra with NumPy

`np.linalg` provides matrix operations: `dot`/`matmul`/`@` for matrix multiplication, `.T` for
transpose, `inv` for the matrix inverse, `det` for the determinant, and `solve` for solving a
system of linear equations `Ax = b`.

In [9]:
# Solution
A = np.array([[2, 0], [0, 3]])
B = np.array([[1, 2], [3, 4]])

print("A @ B (matrix multiplication):\n", A @ B)
print("np.dot(A, B):\n", np.dot(A, B))
print("B transposed:\n", B.T)
print("determinant of B:", np.linalg.det(B))
print("inverse of B:\n", np.linalg.inv(B))

# Solve 2x + y = 5, x + 3y = 10  ->  Ax = b
coeffs = np.array([[2, 1], [1, 3]])
results = np.array([5, 10])
solution = np.linalg.solve(coeffs, results)
print("solution [x, y]:", solution)

A @ B (matrix multiplication):
 [[ 2  4]
 [ 9 12]]
np.dot(A, B):
 [[ 2  4]
 [ 9 12]]
B transposed:
 [[1 3]
 [2 4]]
determinant of B: -2.0000000000000004
inverse of B:
 [[-2.   1. ]
 [ 1.5 -0.5]]
solution [x, y]: [1. 3.]


## 10. Stacking and Resizing

`vstack`/`hstack`/`concatenate` join arrays together along an axis; `array_split` divides one
array into several. `resize` (unlike `reshape`) can change the total number of elements, padding
or repeating data to fit the new shape.

In [10]:
# Solution
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print("vstack (stack rows):\n", np.vstack((x, y)))
print("hstack (stack columns):\n", np.hstack((x, y)))
print("concatenate along axis=0:\n", np.concatenate((x, y), axis=0))
print("concatenate along axis=1:\n", np.concatenate((x, y), axis=1))

to_split = np.arange(9)
print("array_split into 3 parts:", np.array_split(to_split, 3))

small = np.array([1, 2, 3])
print("reshape needs matching size -> resize can pad/repeat instead:")
print("resized to (2,3):\n", np.resize(small, (2, 3)))

vstack (stack rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack (stack columns):
 [[1 2 5 6]
 [3 4 7 8]]
concatenate along axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate along axis=1:
 [[1 2 5 6]
 [3 4 7 8]]
array_split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
reshape needs matching size -> resize can pad/repeat instead:
resized to (2,3):
 [[1 2 3]
 [1 2 3]]
